//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleMVC_UOW_Pattern.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ABC
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CateID { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
